export const GET_PACKAGES_BY_FILTERS = '[FILTERS] : GET_PACKAGES_BY_FILTERS';
export const GET_PACKAGES_BY_FILTERS_SUCCESS =
  '[FILTERS] : GET_PACKAGES_BY_FILTERS_SUCCESS';
export const GET_PACKAGES_BY_FILTERS_ERROR =
  '[FILTERS] : GET_PACKAGES_BY_FILTERS_ERROR';
