export const GET_RECEIVED_REQUEST = '[COACH_REQUEST] : GET_RECEIVED_REQUEST';
export const GET_RECEIVED_REQUEST_SUCCESS =
  '[COACH_REQUEST] : GET_RECEIVED_REQUEST_SUCCESS';
export const GET_RECEIVED_REQUEST_ERROR =
  '[COACH_REQUEST] : GET_RECEIVED_REQUEST_ERROR ';
