export const COACH_UPDATE_INFO = '[COACH_UPDATE_INFO] : COACH_UPDATE_INFO';
export const COACH_UPDATE_INFO_SUCCESS =
  '[COACH_UPDATE_INFO] : COACH_UPDATE_INFO_SUCCESS';
export const COACH_UPDATE_INFO_ERROR =
  '[COACH_UPDATE_INFO] : COACH_UPDATE_INFO_ERROR';
