import { Dimensions, StyleSheet } from 'react-native';
import { colors } from '../../utils/colors';

const { width, height } = Dimensions.get('window');
const CALENDAR_DIMENSIONS = width * 0.9;

export const Style = StyleSheet.create({
  screen: {
    flex: 1,
    width,
    alignItems: 'center',
    backgroundColor: colors.COACH_BACKGROUND_COLOR,
  },
  textScreenTitle: {
    marginTop: 15,
    fontFamily: 'Mulish-Bold',
    fontSize: height * 0.025,
    lineHeight: height * 0.0246,
  },
  scrollContainer: {
    marginBottom: 10,
  },
  childrenContainer: {
    marginLeft: 20,
    marginVertical: 10,
    width: '100%',
    alignSelf: 'flex-start',
  },
  pricingContainer: {
    marginVertical: 10,
    width: '100%',
  },
  childrenContainerCenter: {
    width: '100%',
    paddingBottom: 20,
    paddingHorizontal: 10,
  },
  textInput: {
    height: height * 0.06,
    borderWidth: 1,
    borderColor: colors.PRIMARY,
    borderRadius: 10,
    paddingHorizontal: 15,
    backgroundColor: colors.WHITE,
    marginBottom: 5,
  },
  paragraphInput: {
    backgroundColor: colors.WHITE,
    height: 150,
    // width: width * 0.8,
    borderWidth: 1,
    borderColor: colors.PRIMARY_LOW_OPACITY,
    borderRadius: 5,
    marginBottom: 10,
    paddingTop: 20,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    textAlignVertical: 'top',
    fontFamily: 'Mulish',
    color: colors.SECONDARY,
  },
  fieldContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
  },
  dropDownStyle: {
    height: height * 0.06,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.PRIMARY,
    justifyContent: 'center',
    width: width * 0.35,
    overflow: 'hidden',
    backgroundColor: colors.WHITE,
  },
  textInputDD: {
    fontSize: 12,
  },
  chipStyle: {
    height: 0,
    display: 'none',
  },
  checkBoxCustomStyle: {
    width: '45%',
    marginRight: 5,
  },
  inputNumber: {
    width: '45%',
    marginRight: 25,
  },
  uploadContainer: {
    width: '100%',
    height: height * 0.35,
    backgroundColor: colors.WHITE,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.SPLITTER,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  uploadMainContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  textUpload: {
    fontFamily: 'Mulish',
    textAlign: 'center',
  },
  uploadSecondaryContainer: {
    width: '28%',
    height: height * 0.13,
    backgroundColor: colors.WHITE,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.SPLITTER,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    marginHorizontal: 5,
  },
  checkBoxKids: { width: '22%' },
  customDropDown: {
    width: '25%',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    flexDirection: 'row',
  },
  pricingInputContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    flex: 2,
  },
  currencyIcon: { width: height * 0.03, height: height * 0.03 },
  mainMultiDropdownContainerStyle: {
    justifyContent: 'center',
    height: '90%',
  },
  mainDropdownContainerStyle: {
    justifyContent: 'center',
    height: '100%',
  },
  calendar: {
    width: '90%',
    height: 320,
    alignSelf: 'center',
  },
  imagePreview: {
    width: '100%',
    height: '100%',
    borderRadius: 15,
    backgroundColor: colors.GRAY,
  },
  countryPickerDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    width: '80%',
  },
  locationInfoContainer: {
    flexDirection: 'row',
    width: '100%',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: 15,
    marginHorizontal: 20,
  },
  locationFieldContainer: {
    width: '40%',
    height: height * 0.1,
    justifyContent: 'space-around',
  },
  textLabel: {
    fontFamily: 'Mulish',
    fontSize: height * 0.014,
    color: colors.SECONDARY,
  },
  textError: {
    color: colors.RED,
    fontFamily: 'Poppins',
    fontSize: 10,
    lineHeight: 15,
    marginLeft: 5,
  },
  buttonStyle: {
    margin: 40,
  },
  headerRangeDateContainer: {
    position: 'absolute',
    top: 8,
    left: 25,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 3000,
  },
  textHeaderRangeDateContainer: { fontFamily: 'Mulish-Bold' },
  calendarContainer: {
    width: CALENDAR_DIMENSIONS,
    height: CALENDAR_DIMENSIONS,
    alignSelf: 'center',
    marginBottom: 10,
  },
  textCalendarYear: { color: colors.GRAY },
  galleryContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  removeImageContainer: {
    position: 'absolute',
    right: 10,
    top: 10,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.BLACK_OPACITY,
    zIndex: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeImageIcon: { color: colors.WHITE, fontFamily: 'Mulish-Bold' },
});
