export const GET_NOTIFICATIONS = '[NOTIFICATIONS_LIST] : GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS =
  '[NOTIFICATIONS_LIST] : GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_ERROR =
  '[NOTIFICATIONS_LIST] : GET_NOTIFICATIONS_ERROR';
