export const GET_SESSION_DETAILS = '[DETAILS] : GET_SESSION_DETAILS';
export const GET_SESSION_DETAILS_SUCCESS =
  '[DETAILS] : GET_SESSION_DETAILS_SUCCESS';
export const GET_SESSION_DETAILS_ERROR =
  '[DETAILS] : GET_SESSION_DETAILS_ERROR';

export const GET_PACKAGE_DETAILS = '[DETAILS] : GET_PACKAGE_DETAILS';
export const GET_PACKAGE_DETAILS_SUCCESS =
  '[DETAILS] : GET_PACKAGE_DETAILS_SUCCESS';
export const GET_PACKAGE_DETAILS_ERROR =
  '[DETAILS] : GET_PACKAGE_DETAILS_ERROR';
