export const GET_LANGUAGES = '[BASIC_INFO] : GET_LANGUAGES';
export const GET_LANGUAGES_SUCCESS = '[BASIC_INFO] : GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_ERROR = '[BASIC_INFO] : GET_LANGUAGES_ERROR';

export const SET_BASIC_INFO = '[BASIC_INFO] : SET_BASIC_INFO';
export const SET_BASIC_INFO_SUCCESS = '[BASIC_INFO] : SET_BASIC_INFO_SUCCESS';
export const SET_BASIC_INFO_ERROR = '[BASIC_INFO] : SET_BASIC_INFO_ERROR';
