import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../../../../utils/colors';

const { width, height } = Dimensions.get('window');
export const Style = StyleSheet.create({
  container: {
    flex: 1,
  },
  windowContainer: {
    width,
    alignItems: 'center',
    zIndex: -1,
  },
  buttonSize: {
    width: width * 0.9,
    height: height * 0.0665,
  },
  modalContainer: {
    backgroundColor: colors.MODAL_BACKGROUND,
    height: height,
    marginTop: height * 0.2,
    bottom: 0,
    left: 0,
    right: 0,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    alignItems: 'center',
  },
  textSubTitle: {
    marginVertical: 20,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'Poppins',
  },
  textSubTitleOtp: {
    fontFamily: 'Poppins',
    fontWeight: '600',
    marginVertical: 25,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 18,
    color: colors.OTP_TEXT_COLOR,
  },
  countDownContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  phoneInputContainer: {
    padding: 8,
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.WHITE,
    borderRadius: 10,
    shadowColor: colors.BLACK,
    marginVertical: 20,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    width: width * 0.9,
    marginBottom: 30,
  },
  countryPickerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 10,
    borderRightWidth: 0.6,
    borderColor: colors.LIGHT_GRAY,
    marginRight: 8,
  },
  textStyle: {
    fontSize: 15,
    fontFamily: 'Poppins',
  },
  textInputStyle: {
    fontSize: 15,
    fontFamily: 'Poppins',
    width: width * 0.6,
    height: 50,
  },
  changePasswordContainer: {
    width: width * 0.9,
    height: height * 0.1637,
    backgroundColor: colors.WHITE,
    justifyContent: 'space-evenly',
    borderRadius: 20,
    paddingLeft: 10,
    shadowColor: colors.BLACK,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginVertical: 30,
  },
  textError: {
    color: colors.RED,
    fontFamily: 'Poppins',
    fontSize: 10,
    lineHeight: 15,
  },
  borderBottom: {
    borderBottomColor: colors.SPLITTER,
    borderBottomWidth: 0.8,
  },
  inputContainer: {
    height: 55,
    justifyContent: 'center',
  },
  countDownBackground: {
    backgroundColor: colors.MODAL_BACKGROUND,
  },
  countDownSeparator: { bottom: 2 },
  otpContainerStyle: { width: '90%', height: '10%' },
  otpInputFieldStyle: {
    borderRadius: 20,
    backgroundColor: colors.WHITE,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.BLACK,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    marginVertical: 20,
    textAlign: 'center',
    height: 66,
    width: 66,
    fontSize: 25,
    fontFamily: 'Mulish-Bold',
    lineHeight: 31,
    color: colors.BLACK,
  },
});
