export const GET_SURFER_INFO = '[SURFER_PROFILE] : GET_SURFER_INFO';
export const GET_SURFER_INFO_SUCCESS =
  '[SURFER_PROFILE] : GET_SURFER_INFO_SUCCESS';
export const GET_SURFER_INFO_ERROR = '[SURFER_PROFILE] : GET_SURFER_INFO_ERROR';

export const GET_REVIEWS = '[SURFER_PROFILE] : GET_REVIEWS';
export const GET_REVIEWS_SUCCESS = '[SURFER_PROFILE] : GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_ERROR = '[SURFER_PROFILE] : GET_REVIEWS_ERROR';
