export const GET_REQUEST_DETAILS =
  '[REQUEST_CONFIRMATION] : GET_REQUEST_DETAILS';
export const GET_REQUEST_DETAILS_SUCCESS =
  '[REQUEST_CONFIRMATION] : GET_REQUEST_DETAILS_SUCCESS';
export const GET_REQUEST_DETAILS_ERROR =
  '[REQUEST_CONFIRMATION] : GET_REQUEST_DETAILS_ERROR';

export const ACCEPT_REQUEST = '[REQUEST_CONFIRMATION] : ACCEPT_REQUEST ';
export const ACCEPT_REQUEST_SUCCESS =
  '[REQUEST_CONFIRMATION] : ACCEPT_REQUEST_SUCCESS';
export const ACCEPT_REQUEST_ERROR =
  '[REQUEST_CONFIRMATION] : ACCEPT_REQUEST_ERROR';
