export const BOOK_OFFER = '[REQUEST_SESSION] : BOOK_OFFER';
export const BOOK_OFFER_SUCCESS = '[REQUEST_SESSION] : BOOK_OFFER_SUCCESS';
export const BOOK_OFFER_ERROR = '[REQUEST_SESSION] : BOOK_OFFER_ERROR';
