export const CANCEL_REQUEST = '[REQUEST_CANCELLATION] : CANCEL_REQUEST';
export const CANCEL_REQUEST_SUCCESS =
  '[REQUEST_CANCELLATION] : CANCEL_REQUEST_SUCCESS';
export const CANCEL_REQUEST_ERROR =
  '[REQUEST_CANCELLATION] : CANCEL_REQUEST_ERROR';

export const SUGGEST_TIME_SLOT = '[REQUEST_CANCELLATION] : SUGGEST_TIME_SLOT';
export const SUGGEST_TIME_SLOT_SUCCESS =
  '[REQUEST_CANCELLATION] : SUGGEST_TIME_SLOT_SUCCESS';
export const SUGGEST_TIME_SLOT_ERROR =
  '[REQUEST_CANCELLATION] : SUGGEST_TIME_SLOT_ERROR';

export const ACCEPT_SUGGESTION = '[REQUEST_CANCELLATION] : ACCEPT_SUGGESTION';
export const ACCEPT_SUGGESTION_SUCCESS =
  '[REQUEST_CANCELLATION] : ACCEPT_SUGGESTION_SUCCESS';
export const ACCEPT_SUGGESTION_ERROR =
  '[REQUEST_CANCELLATION] : ACCEPT_SUGGESTION_ERROR';
