export const GET_PAST_REQUEST = '[COACH_REQUEST] : GET_PAST_REQUEST';
export const GET_PAST_REQUEST_SUCCESS =
  '[COACH_REQUEST] : GET_PAST_REQUEST_SUCCESS';
export const GET_PAST_REQUEST_ERROR =
  '[COACH_REQUEST] : GET_PAST_REQUEST_ERROR';
