export const GET_AVAILABALE_PACKAGES = '[DISCOVER] : GET_AVAILABLE_PACKAGES';
export const GET_AVAILABALE_PACKAGES_SUCCESS =
  '[DISCOVER] : GET_AVAILABLE_PACKAGES_SUCCESS';
export const GET_AVAILABALE_PACKAGES_ERROR =
  '[DISCOVER] : GET_AVAILABLE_PACKAGES_ERROR';

export const GET_RECENT_PACKAGES = '[DISCOVER] : GET_RECENT_PACKAGES';
export const GET_RECENT_PACKAGES_SUCCESS =
  '[DISCOVER] : GET_RECENT_PACKAGES_SUCCESS';
export const GET_RECENT_PACKAGES_ERROR =
  '[DISCOVER] : GET_RECENT_PACKAGES_ERROR';

export const GET_AVAILABALE_SESSIONS = '[HOME] : GET_AVAILABLE_SESSIONS';
export const GET_AVAILABALE_SESSIONS_SUCCESS =
  '[HOME] : GET_AVAILABALE_SESSIONS_SUCCESS';
export const GET_AVAILABALE_SESSIONS_ERROR =
  '[HOME] : GET_AVAILABALE_SESSIONS_ERROR';

export const GET_RECENT_SESSIONS = '[DISCOVER] : GET_RECENT_SESSIONS';
export const GET_RECENT_SESSIONS_SUCCESS =
  '[DISCOVER] : GET_RECENT_SESSIONS_SUCCESS';
export const GET_RECENT_SESSIONS_ERROR =
  '[DISCOVER] : GET_RECENT_SESSIONS_ERROR';
