export const GET_EVENTS = '[COACH_SCHEDULE] : GET_EVENTS';
export const GET_EVENTS_SUCCESS = '[COACH_SCHEDULE] : GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = '[COACH_SCHEDULE] : GET_EVENTS_ERROR';
