import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors } from '../../utils/colors';
import { ANDROID } from '../../config/app.constant';
const { width, height } = Dimensions.get('window');

export const Style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.COACH_BACKGROUND_COLOR,
    alignItems: 'center',
    paddingTop: Platform.OS === ANDROID ? 20 : 45,
  },
  coverContainer: {
    height: height / 6,
    width: width * 0.9,
    paddingHorizontal: 10,
    paddingTop: 20,
    alignSelf: 'center',
    borderRadius: 30,
    opacity: 0.9,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.GRAY,
  },
  imageButtonContainer: {
    height: 50,
    width: 50,
    backgroundColor: colors.WHITE_SMALL_OPACITY,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profilePicture: {
    height: height / 7,
    width: height / 7,
    top: -height / 14,
    borderColor: colors.WHITE,
    borderRadius: 10,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  blurredProfile: {
    height: height / 7,
    width: height / 7,
    overflow: 'hidden',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.GRAY,
  },
  generalInfoContainer: {
    top: -height / 20,
    alignSelf: 'center',
  },
  fullNameText: {
    fontFamily: 'Mulish-Bold',
    fontSize: 20,
    color: colors.SECONDARY,
    shadowColor: colors.SECONDARY,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
    textAlign: 'center',
    paddingHorizontal: '5%',
  },
  coachTitle: {
    textAlign: 'center',
    fontSize: 15,
    color: colors.SECONDARY,
    opacity: 0.5,
  },
  locationContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  locationText: {
    color: colors.BLACK,
    opacity: 0.5,
    marginHorizontal: 10,
  },
  inputsContainer: {
    top: -height / 40,
    width: width * 0.85,
  },
  inputLabel: {
    fontFamily: 'Mulish',
    fontSize: height / 50,
    color: colors.BLACK,
    fontWeight: '500',
    marginBottom: 5,
  },
  inputError: {
    fontFamily: 'Mulish',
    fontSize: height / 60,
    color: colors.RED,
    fontWeight: '500',
    marginBottom: 5,
    width: '90%',
  },
  inputContainer: {
    backgroundColor: colors.WHITE,
    height: 55,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  updateButton: {
    alignSelf: 'center',
    marginTop: 30,
    marginBottom: 20,
  },
  removeImageContainer: {
    position: 'absolute',
    right: 10,
    top: 10,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.BLACK_OPACITY,
    zIndex: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeImageIcon: {
    color: colors.WHITE,
    fontFamily: 'Mulish-Bold',
  },
  removeCoverImageContainer: {
    position: 'absolute',
    right: 10,
    top: 30,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.BLACK_OPACITY,
    zIndex: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  goBackButtonContainer: {
    position: 'absolute',
    zIndex: 1,
    top: 30,
    left: 20,
    backgroundColor: colors.WHITE_SMALL_OPACITY,
    height: 50,
    width: 50,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dotContainer: {
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 2,
    width: '90%',
  },
  dot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.SECONDARY,
    marginRight: 3,
  },
  otpModalContainer: {
    width,
    height,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.BLUE_MODAL_BACKGROUND,
    zIndex: 9999,
  },
});
