export const AUTH_REGISTER = '[AUTH_REGISTER] : CREATE_ACCOUNT';
export const AUTH_REGISTER_SUCCESS = '[AUTH_REGISTER] : CREATE_ACCOUNT_SUCCESS';
export const AUTH_REGISTER_ERROR = '[AUTH_REGISTER] : CREATE_ACCOUNT_ERROR';

export const AUTH_PHONE_VERIFICATION =
  '[AUTH_REGISTER] : AUTH_PHONE_VERIFICATION';
export const AUTH_PHONE_VERIFICATION_SUCCESS =
  '[AUTH_REGISTER] : AUTH_PHONE_VERIFICATION_SUCCESS';
export const AUTH_PHONE_VERIFICATION_ERROR =
  '[AUTH_REGISTER] : AUTH_PHONE_VERIFICATION_ERROR';

export const AUTH_OTP_VERIFICATION = '[AUTH_REGISTER] : AUTH_OTP_VERIFICATION';
export const AUTH_OTP_VERIFICATION_SUCCESS =
  '[AUTH_REGISTER] : AUTH_OTP_VERIFICATION_SUCCESS';
export const AUTH_OTP_VERIFICATION_ERROR =
  '[AUTH_REGISTER] : AUTH_OTP_VERIFICATION_ERROR';

export const AUTH_REST_PASSWORD = '[AUTH_SIGNIN] : AUTH_REST_PASSWORD';
export const AUTH_REST_PASSWORD_SUCCESS =
  '[AUTH_SIGNIN] :AUTH_REST_PASSWORD_SUCCESS';
export const AUTH_REST_PASSWORD_ERROR =
  '[AUTH_SIGNIN] : AUTH_OTP_VERIFICATION_ERROR';

export const CHECK_CURRENT = '[HOME] : CHECK_CURRENT';
export const CHECK_CURRENT_SUCCESS = '[HOME] : CHECK_CURRENT_SUCCESS';
export const CHECK_CURRENT_ERROR = '[HOME] : CHECK_CURRENT_ERROR';

export const LOGOUT_USER = '[AUTH] : LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = '[AUTH] :LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = '[AUTH] : LOGOUT_USER_ERROR';

export const DISABLE_ACCOUNT = '[DISABLE_ACCOUNT] : DISABLE_ACCOUNT';
export const DISABLE_ACCOUNT_SUCCESS =
  '[DISABLE_ACCOUNT] :DISABLE_ACCOUNT_SUCCESS';
export const DISABLE_ACCOUNT_ERROR =
  '[DISABLE_ACCOUNT] : DISABLE_ACCOUNT_ERROR';
export const OPEN_MODAL_ACCOUNT = '[DISABLE_ACCOUNT] : OPEN_MODAL_ACCOUNT';
export const CLOSE_MODAL_ACCOUNT = '[DISABLE_ACCOUNT] : CLOSE_MODAL_ACCOUNT';

export const ACTIVATE_ACCOUNT = '[ACTIVATE_ACCOUNT] : ACTIVATE_ACCOUNT';
export const ACTIVATE_ACCOUNT_SUCCESS =
  '[ACTIVATE_ACCOUNT] :ACTIVATE_ACCOUNT_SUCCESS';
export const ACTIVATE_ACCOUNT_ERROR =
  '[ACTIVATE_ACCOUNT] : ACTIVATE_ACCOUNT_ERROR';
