export const CLOSE_MODAL = '[HOME] : CLOSE_MODAL';
export const OPEN_MODAL = '[HOME] : OPEN_MODAL';

export const CLOSE_SUCCESS_MODAL = '[HOME] : CLOSE_SUCCESS_MODAL';
export const OPEN_SUCCESS_MODAL = '[HOME] : OPEN_SUCCESS_MODAL';
export const CLOSE_TOAST = '[HOME] : CLOSE_TOAST';
export const OPEN_TOAST = '[HOME] : OPEN_TOAST';

export const AUTH_SIGNIN = '[AUTH] : AUTH_SIGNIN';
export const AUTH_SIGNIN_SUCCESS = '[AUTH] : AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_ERROR = '[AUTH] : AUTH_SIGNIN_ERROR';

export const OPEN_MODAL_PAST_EVENTS = '[PAST_EVENTS] : OPEN_MODAL_PAST_EVENTS';
export const CLOSE_MODAL_PAST_EVENTS =
  '[PAST_EVENTS] : CLOSE_MODAL_PAST_EVENTS';

export const ADD_BETA_REVIEW = '[BETA_TEST] : ADD_BETA_REVIEW';
export const ADD_BETA_REVIEW_SUCCESS = '[BETA_TEST] : ADD_BETA_REVIEW_SUCCESS';
export const ADD_BETA_REVIEW_ERROR = '[BETA_TEST] : ADD_BETA_REVIEW_ERROR';

export const OPEN_BETA_TEST_MODAL = '[BETA_TEST] : OPEN_MODAL';
export const CLOSE_BETA_TEST_MODAL = '[BETA_TEST] : CLOSE_MODAL';

export const DISPLAY_STICKER = '[BETA_TEST] : DISPLAY_STICKER';
export const HIDE_STICKER = '[BETA_TEST] : HIDE_STICKER';

export const OPEN_BETA_GENERAL_TEST_MODAL =
  '[BETA_TEST] : OPEN_BETA_GENERAL_TEST_MODAL';
export const CLOSE_BETA_GENERAL_TEST_MODAL =
  '[BETA_TEST] : CLOSE_BETA_GENERAL_TEST_MODAL';

export const ADD_BETA_GENERAL_REVIEW = '[BETA_TEST] : ADD_BETA_GENERAL_REVIEW';
export const ADD_BETA_GENERAL_REVIEW_SUCCESS =
  '[BETA_TEST] : ADD_BETA_GENERAL_REVIEW_SUCCESS';
export const ADD_BETA_GENERAL_REVIEW_ERROR =
  '[BETA_TEST] : ADD_BETA_GENERAL_REVIEW_ERROR';

export const SET_DATE_TO_SHOW_FEEDBACK_MODAL =
  '[BETA_TEST] : SET_DATE_TO_SHOW_FEEDBACK_MODAL';
export const SET_DATE_TO_SHOW_FEEDBACK_MODAL_SUCCESS =
  '[BETA_TEST] : SET_DATE_TO_SHOW_FEEDBACK_MODAL_SUCCESS';
export const SET_DATE_TO_SHOW_FEEDBACK_MODAL_ERROR =
  '[BETA_TEST] : SET_DATE_TO_SHOW_FEEDBACK_MODAL_ERROR';

export const GET_DATE_TO_SHOW_FEEDBACK_MODAL =
  '[BETA_TEST] : GET_DATE_TO_SHOW_FEEDBACK_MODAL';
export const GET_DATE_TO_SHOW_FEEDBACK_MODAL_SUCCESS =
  '[BETA_TEST] : GET_DATE_TO_SHOW_FEEDBACK_MODAL_SUCCESS';
export const GET_DATE_TO_SHOW_FEEDBACK_MODAL_ERROR =
  '[BETA_TEST] : GET_DATE_TO_SHOW_FEEDBACK_MODAL_ERROR';

export const DISPLAY_SUCCESS_BETA_TEST_MODAL =
  '[BETA_TEST] : DISPLAY_SUCCESS_BETA_TEST_MODAL';
export const HIDE_SUCCESS_BETA_TEST_MODAL =
  '[BETA_TEST] : HIDE_SUCCESS_BETA_TEST_MODAL';

export const HAS_NEW_NOTIFICATION = '[DRAWER] : HAS_NEW_NOTIFICATION';
export const SEEN_NEW_NOTIFICATION = '[DRAWER] : SEEN_NEW_NOTIFICATION';
