export const GET_CITIES = '[ADD_OFFER] : GET_CITIES';
export const GET_CITIES_SUCCESS = '[ADD_OFFER] : GET_CITIES_SUCCESS';
export const GET_CITIES_ERROR = '[ADD_OFFER] : GET_CITIES_ERROR';

export const ADD_OFFER = '[ADD_OFFER] : ADD_OFFER';
export const ADD_OFFER_SUCCESS = '[ADD_OFFER] : ADD_OFFER_SUCCESS';
export const ADD_OFFER_ERROR = '[ADD_OFFER] : ADD_OFFER_ERROR';

export const GET_SKILLS = '[ADD_OFFER] : GET_SKILLS';
export const GET_SKILLS_SUCCESS = '[ADD_OFFER] : GET_SKILLS_SUCCESS';
export const GET_SKILLS_ERROR = '[ADD_OFFER] : GET_SKILLS_ERROR';

export const GET_OFFER = '[ADD_OFFER] : GET_OFFER';
export const GET_OFFER_SUCCESS = '[ADD_OFFER] : GET_OFFER_SUCCESS';
export const GET_OFFER_ERROR = '[ADD_OFFER] : GET_OFFER_ERROR';

export const DELETE_OFFER = '[ADD_OFFER] : DELETE_OFFER';
export const DELETE_OFFER_SUCCESS = '[ADD_OFFER] : DELETE_OFFER_SUCCESS';
export const DELETE_OFFER_ERROR = '[ADD_OFFER] : DELETE_OFFER_ERROR';

export const GET_STATES = '[ADD_OFFER] : GET_STATES';
export const GET_STATES_SUCCESS = '[ADD_OFFER] : GET_STATES_SUCCESS';
export const GET_STATES_ERROR = '[ADD_OFFER] : GET_STATES_ERROR';

export const GET_STATES_CITIES = '[ADD_OFFER] : GET_STATES_CITIES';
export const GET_STATES_CITIES_SUCCESS =
  '[ADD_OFFER] : GET_STATES_CITIES_SUCCESS';
export const GET_STATES_CITIES_ERROR = '[ADD_OFFER] : GET_STATES_CITIES_ERROR';
