import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../../../../utils/colors';

const { height, width } = Dimensions.get('screen');
export const Style = StyleSheet.create({
  keyboardAvoidContainer: {
    justifyContent: 'space-around',
  },
  screenContainer: {
    height,
    justifyContent: 'space-around',
  },
  imageContainer: {
    flex: 1,
    width,
  },
  viewContainer: {
    backgroundColor: colors.SECONDARY_OPACITY,
    paddingHorizontal: 19,
    flex: 1,
    width,
    height,
  },
  logoContainer: {
    flex: 0.2,
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  arrowLeftStyle: {
    position: 'absolute',
    top: 30,
    left: 10,
    zIndex: 1,
  },
  logoLetterContainer: {
    backgroundColor: colors.WHITE,
    paddingHorizontal: 5,
    paddingVertical: 18,
    borderRadius: 5,
    width: 100,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textContainer: {
    flex: 0.15,
    justifyContent: 'space-around',
  },
  textBoldTitle: {
    fontFamily: 'Poppins-Bold',
    fontSize: height * 0.0344,
    lineHeight: height * 0.0418,
    color: colors.WHITE,
  },
  textRegularTitle: {
    fontFamily: 'Poppins',
    fontSize: height * 0.0209,
    fontWeight: '400',
    lineHeight: 22,
    color: colors.WHITE,
  },
  formContainer: {
    flex: 0.5,
    justifyContent: 'space-around',
  },
  infoContainer: {
    backgroundColor: colors.WHITE,
    height: height * 0.4,
    borderRadius: 10,
    paddingLeft: 10,
    justifyContent: 'space-evenly',
    marginTop: 10,
    paddingBottom: 10,
  },
  bottomContainer: {
    flex: 0.25,
    marginTop: 15,
  },
  bottomTextContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textBottom: (primary) => ({
    color: primary ? colors.PRIMARY : colors.WHITE,
    fontFamily: 'Poppins',
    fontSize: 15,
    lineHeight: 20,
    textAlign: 'center',
    marginHorizontal: 2,
  }),
  phoneInputContainer: {
    padding: 8,
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.WHITE,
    borderRadius: 10,
    shadowColor: colors.BLACK,
    marginVertical: 20,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    width: width * 0.9,
    marginBottom: 30,
  },
  phonInput: {
    width: width * 0.85,
    height: 35,
  },
  countryPickerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 10,
    borderRightWidth: 0.6,
    borderColor: colors.LIGHT_GRAY,
    marginRight: 8,
  },
  textInputStyle: {
    paddingHorizontal: 10,
    fontSize: 15,
  },
  textError: {
    color: colors.RED,
    fontFamily: 'Poppins',
    fontSize: 10,
    lineHeight: 15,
  },
  borderBottom: {
    borderBottomColor: colors.SPLITTER,
    borderBottomWidth: 0.8,
  },
  tabBar: {
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: height * 0.058,
    width: width * 0.8,
    borderRadius: 24,
    backgroundColor: colors.WHITE,
    padding: 4,
  },
  tab: (backColor) => ({
    justifyContent: 'center',
    alignItems: 'center',
    width: width * 0.25,
    height: height * 0.045,
    borderRadius: 24,
    backgroundColor: backColor,
  }),
  textTab: (color) => ({
    color: color,
    fontFamily: 'Mulish-Bold',
  }),
  IconButtonStyle: {
    marginVertical: 10,
  },
  customInputStyle: {
    height: height * 0.067,
  },
  phoneVerificationTopContainer: {
    width,
    height,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
    zIndex: 9999,
  },
});
