export const GET_IMAGES = '[COACH_DETAILS] : GET_IMAGES';
export const GET_IMAGES_SUCCESS = '[COACH_DETAILS] : GET_IMAGES_SUCCESS';
export const GET_IMAGES_ERROR = '[COACH_DETAILS] : GET_IMAGES_ERROR';

export const GET_DESCRIPTION = '[COACH_DETAILS] : GET_DESCRIPTION';
export const GET_DESCRIPTION_SUCCESS =
  '[COACH_DETAILS] : GET_DESCRIPTION_SUCCESS';
export const GET_DESCRIPTION_ERROR = '[COACH_DETAILS] : GET_DESCRIPTION_ERROR';

export const GET_REVIEWS = '[COACH_DETAILS] : GET_REVIEWS';
export const GET_REVIEWS_SUCCESS = '[COACH_DETAILS] : GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_ERROR = '[COACH_DETAILS] : GET_REVIEWS_ERROR';

export const GET_OFFERS = '[COACH_DETAILS] : GET_OFFERS';
export const GET_OFFERS_SUCCESS = '[COACH_DETAILS] : GET_OFFERS_SUCCESS';
export const GET_OFFERS_ERROR = '[COACH_DETAILS] : GET_OFFERS_ERROR';
