import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../../utils/colors';
const { width, height } = Dimensions.get('window');
export const Style = StyleSheet.create({
  container: {
    width: width * 0.9,
    height: height * 0.35,
    minHeight: 270,
    marginBottom: 20,
    borderRadius: 10,
    justifyContent: 'space-around',
    backgroundColor: colors.WHITE_BACKGROUND,
    borderWidth: 4,
    borderColor: colors.WHITE,
    alignSelf: 'center',
  },
  icon: {
    alignSelf: 'flex-end',
    paddingRight: 18,
  },
  infoContainer: {
    alignItems: 'center',
  },
  name: {
    fontFamily: 'Mulish',
    fontSize: height * 0.022,
    lineHeight: 22,
    fontWeight: '600',
    color: colors.SECONDARY,
  },
  type: {
    fontFamily: 'Mulish',
    fontSize: 10,
    fontWeight: '400',
    color: colors.SECONDARY,
  },
  bioContainer: {
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  bio: {
    textAlign: 'center',
    fontFamily: 'Mulish',
    fontSize: 10,
    lineHeight: 16.5,
    fontWeight: '400',
    color: colors.BLACK,
  },
  link: {
    textAlign: 'center',
    fontFamily: 'Mulish',
    fontSize: 13,
    textDecorationLine: 'underline',
    color: colors.PRIMARY_DARK,
  },
  avatar: {
    alignSelf: 'center',
    width: height * 0.09,
    height: height * 0.09,
    borderRadius: (height * 0.09) / 2,
    backgroundColor: colors.GRAY,
  },
  avatarContainer: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    width: height * 0.1,
    height: height * 0.1,
    borderRadius: (height * 0.1) / 2,
    borderWidth: 3,
    borderStyle: 'dashed',
    borderColor: colors.ORANGE,
    marginBottom: 5,
  },
  tabBar: {
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: height * 0.058,
    width: width * 0.8,
    borderRadius: 24,
    backgroundColor: colors.WHITE,
    padding: 4,
  },
  tab: (backColor) => ({
    justifyContent: 'center',
    alignItems: 'center',
    width: width * 0.25,
    height: height * 0.045,
    borderRadius: 24,
    backgroundColor: backColor,
  }),
  textTab: (color) => ({
    color: color,
    fontFamily: 'Mulish-Bold',
  }),
  rating: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginLeft: 6,
  },
  value: {
    marginHorizontal: 3,
    fontSize: 13,
    color: colors.BLACK_REVIEW,
    fontFamily: 'Mulish',
    lineHeight: 20,
    fontWeight: '600',
  },
  nameContainer: {
    flexDirection: 'row',
  },
  coverPicture: {
    width: '100%',
    height: height * 0.15,
    borderRadius: 10,
  },
  profileInfoContainer: {
    top: -45,
    justifyContent: 'space-between',
    height: '45%',
  },
});
