export const GET_BOOKING = '[BOOKING_LIST] : GET_BOOKING';
export const GET_BOOKING_SUCCESS = '[BOOKING_LIST] : GET_BOOKING_SUCCESS';
export const GET_BOOKING_ERROR = '[BOOKING_LIST] : GET_BOOKING_ERROR';

export const CANCEL_BOOKING = '[BOOKING_LIST] : CANCEL_BOOKING';
export const CANCEL_BOOKING_SUCCESS = '[BOOKING_LIST] : CANCEL_BOOKING_SUCCESS';
export const CANCEL_BOOKING_ERROR = '[BOOKING_LIST] : CANCEL_BOOKING_ERROR';
