export const UPDATE_INFO = '[UPDATE_INFO] : UPDATE_INFO';
export const UPDATE_INFO_SUCCESS = '[UPDATE_INFO] : UPDATE_INFO_SUCCESS';
export const UPDATE_INFO_ERROR = '[UPDATE_INFO] : UPDATE_INFO_ERROR';
