export const GET_TOKEN = '[DISCUSSION] : GET_TOKEN';
export const GET_TOKEN_SUCCESS = '[DISCUSSION] : GET_TOKEN_SUCCESS';
export const GET_TOKEN_ERROR = '[DISCUSSION] : GET_TOKEN_ERROR';

export const SEND_SMS = '[DISCUSSION] : SEND_SMS';
export const SEND_SMS_SUCCESS = '[DISCUSSION] : SEND_SMS_SUCCESS';
export const SEND_SMS_ERROR = '[DISCUSSION] : SEND_SMS_ERROR';
